services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sisclinic
      POSTGRES_PASSWORD: sisclinic
      POSTGRES_DB: sisclinic
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: