"""empty message

Revision ID: 236abaaff03e
Revises: cb0b347e0981
Create Date: 2025-01-28 08:54:27.513519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236abaaff03e'
down_revision: Union[str, None] = 'cb0b347e0981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'scheduler_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('scheduler_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
