"""empty message

Revision ID: 2a987e8fec16
Revises: f5d172db962c
Create Date: 2024-12-30 18:30:31.812373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a987e8fec16'
down_revision: Union[str, None] = 'f5d172db962c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('room', sa.String(), nullable=False))
    op.drop_column('schedule', 'Room')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('Room', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('schedule', 'room')
    # ### end Alembic commands ###
