"""empty message

Revision ID: 4c6ee5442648
Revises: 9bb652bb3565
Create Date: 2025-01-05 18:50:45.505353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6ee5442648'
down_revision: Union[str, None] = '9bb652bb3565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'active')
    # ### end Alembic commands ###
