"""empty message

Revision ID: 6aee6fa74340
Revises: cde7a53e5701
Create Date: 2025-01-16 21:45:18.395651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6aee6fa74340'
down_revision: Union[str, None] = 'cde7a53e5701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_deactivation', sa.Column('date_limit', sa.DateTime(), nullable=False))
    op.drop_column('schedule_deactivation', 'date_limmit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_deactivation', sa.Column('date_limmit', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('schedule_deactivation', 'date_limit')
    # ### end Alembic commands ###
