"""empty message

Revision ID: b6fd2ec65b85
Revises: bed211e5a434
Create Date: 2025-01-26 21:42:53.098069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6fd2ec65b85'
down_revision: Union[str, None] = 'bed211e5a434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('scheduler_id', sa.Integer(), nullable=False))
    op.add_column('schedule', sa.Column('recurrence_weekday', sa.Integer(), nullable=True))
    op.add_column('schedule', sa.Column('recurrence_time', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'schedule', ['scheduler_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule', type_='unique')
    op.drop_column('schedule', 'recurrence_time')
    op.drop_column('schedule', 'recurrence_weekday')
    op.drop_column('schedule', 'scheduler_id')
    # ### end Alembic commands ###
