"""empty message

Revision ID: cac75fcf46c7
Revises: f38fcaceb733
Create Date: 2024-12-30 19:00:21.664943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac75fcf46c7'
down_revision: Union[str, None] = 'f38fcaceb733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('type_scheduled', sa.String(), nullable=False))
    op.drop_column('schedule', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('schedule', 'type_scheduled')
    # ### end Alembic commands ###
