"""empty message

Revision ID: cde7a53e5701
Revises: 33d4f7713013
Create Date: 2025-01-16 18:28:54.187554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde7a53e5701'
down_revision: Union[str, None] = '33d4f7713013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_deactivation', sa.Column('date_limmit', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_deactivation', 'date_limmit')
    # ### end Alembic commands ###
