"""empty message

Revision ID: eaf6fe70f386
Revises: 3ec2a0100422
Create Date: 2024-12-29 14:32:50.135568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf6fe70f386'
down_revision: Union[str, None] = '3ec2a0100422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    op.add_column('professional_record', sa.Column('street', sa.String(), nullable=False))
    op.add_column('professional_record', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('professional_record', sa.Column('not_number', sa.Boolean(), nullable=True))
    op.add_column('professional_record', sa.Column('neighborhood', sa.String(), nullable=False))
    op.add_column('professional_record', sa.Column('city', sa.String(), nullable=False))
    op.add_column('professional_record', sa.Column('cep', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professional_record', 'cep')
    op.drop_column('professional_record', 'city')
    op.drop_column('professional_record', 'neighborhood')
    op.drop_column('professional_record', 'not_number')
    op.drop_column('professional_record', 'number')
    op.drop_column('professional_record', 'street')
    op.create_table('address',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('not_number', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('neighborhood', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cep', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='address_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='address_pkey')
    )
    # ### end Alembic commands ###
